<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260604113406 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Auto-generated migration, made defensive: exact duplicate of Version20260604112000 (same ADD), historically re-generated by mistake. No-ops when the column already exists.';
    }

    public function up(Schema $schema): void
    {
        if ($this->tableExists('hodina_setting') && !$this->columnExists('hodina_setting', 'delivered_communes')) {
            $this->addSql('ALTER TABLE hodina_setting ADD delivered_communes LONGTEXT DEFAULT NULL');
        }
    }

    public function down(Schema $schema): void
    {
        if ($this->tableExists('hodina_setting') && $this->columnExists('hodina_setting', 'delivered_communes')) {
            $this->addSql('ALTER TABLE hodina_setting DROP delivered_communes');
        }
    }

    private function tableExists(string $tableName): bool
    {
        $result = $this->connection->fetchOne(
            'SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?',
            [$tableName],
        );

        return (int) $result > 0;
    }

    private function columnExists(string $tableName, string $columnName): bool
    {
        $result = $this->connection->fetchOne(
            'SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?',
            [$tableName, $columnName],
        );

        return (int) $result > 0;
    }
}
